INFO     E:\python半成熟自动化\退伍军人接口自动化测试\退伍军人:test_数据分发.py:36 用例【名称超界】开始测试,这是第【4】条用例
发起请求的地址是------>:http://192.168.0.253:8080/gateways/archive-distribute/create
WARNING  E:\python半成熟自动化\退伍军人接口自动化测试\退伍军人:test_数据分发.py:66 断言失败----期望结果是>>>>>>>:{'code': 400, 'message': '长度过长', 'data': None}-----响应结果是>>>>>>>:{'code': 400, 'message': "\r\n### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'NAME' at row 1\r\n### The error may exist in org/mindrive/system/dao/mapper/ArchiveDistributeBatchRecordMapper.java (best guess)\r\n### The error may involve org.mindrive.system.dao.mapper.ArchiveDistributeBatchRecordMapper.insert-Inline\r\n### The error occurred while setting parameters\r\n### SQL: INSERT INTO ARCHIVE_DISTRIBUTE_BATCH_RECORD  ( ID, `organization_id`, `no`, `prefix`, `index`, `name`, `remark`, `status`, `creator`, `created_at` )  VALUES  ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )\r\n### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'NAME' at row 1\n; Data truncation: Data too long for column 'NAME' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'NAME' at row 1", 'data': None}
INFO     E:\python半成熟自动化\退伍军人接口自动化测试\退伍军人:test_数据分发.py:73 <<<<<<<<<<<<<<<<<用例【名称超界】测试结束>>>>>>>>>>>>>>>>>